language: node_js
node_js:
  - "node"
script:
  -
deploy:
  provider: firebase
  token:
    secure: "abHkIVZt/NAZN8ANgpAdHdLKFOCiKuiNmZbWFM6eCJ50WKUGPyXqe15qKXf6hTyijNTjf0S8LFeSAaa21MoXYd4djrcydkYD9hwOQ+RdIFW5zv2kxR+c5QUZ7L9MB3srB6Y7bWxxK4LzW7zTkPJJTNCIV0prMmrb+2PyosQMzQIarPEoNx2ZtArhtXCn+qKsShhQHVfNxM2qJ+TNidRla9P3WbDOQMQJ3jN+MSojs1nSVCPQ3UDi4uefVo/WQ8/saYR2vwAVj9WUr2kozzBMH8ghaRdrxretFAUSRDOESiDl72JRA02awcL7WdTtSE6SAbtQL+YA7uGAEmc0SkOwZIFzYKwCU67Hyk73xJaKvRLuySXSMEKFh/2x/nNoTJp0wmAZ06vFoGtbXtkRbP5VSTTX7g3tMRAIyz9yPk7c+38zqJiBeBI5xFqYuKMgV9K+69LO7YNp1AXw4ob7jqOeusEXZ9nvMkvRkgIDXlCYRu7ix7VGhZ3PxakRDZhF90bgRw2OyGmnBKMHoV3Ni0++ZUhBIxcbwn97xbYMqxv2tQjFIfkIcinpSoKEfYiqdio0K6joQdZjh+xqbw/SDzudYXiNySCNK34m1RQ4kCC1Erm+quMTC6cu0t14spEpU5e2ICVSY6zuDBXOys1K7nLcF4hv3pXyVX+s4P075Yb+Zu4="
